### ISSUE TITLE
A little showcase

### ISSUE THREAD

**Issue by nyngwang** [iruzo/matrix-nvim#1]
Just want to say I love this theme! (I chose `WinBar` to `#242423` but you might recommend another one since I have no much color-sense)

<img src="https://user-images.githubusercontent.com/24765272/227789618-79a0a714-63f6-445b-b6c2-6e61c6321804.png" width="700">

(feel free to use it in promotion)
(feat. [NeoTerm.lua](https://github.com/nyngwang/NeoTerm.lua) [noice.nvim](https://github.com/folke/noice.nvim) [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo) [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) [lualine.nvim](https://github.com/nvim-lualine/lualine.nvim) [nvim-navic](https://github.com/SmiteshP/nvim-navic) [tabby.nvim](https://github.com/nanozuki/tabby.nvim) )

**Comment by iruzo** [comment]
Hey, thanks for showing me NeoTerm and Navic, I didn't know about those plugins and they seem really cool.

Talking about colors, I would recommend using `#113311` for WinBar if you do not want to use the same black as I use for background (`#0d0208`).
